# Matrices

In [108]:
import numpy as np

In [109]:
#Numpy array
revenue= np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [110]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

 + Broadcasting in numpy: If shape of 2 matrix is not same it will try to expand it.
+ price_per_unit=np.array([[1000,400,220],[1000,400,220],[1000,400,220]])
* So, we use np.dot()

In [111]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [112]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

## Exercise

In [113]:
revenue_in_usd=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [114]:
revenue_in_rupees = revenue_in_usd*80
revenue_in_rupees

array([[16000, 17600, 20000],
       [ 5440,  6320,  8400],
       [ 8800, 11200, 14400],
       [ 6400,  6800,  7200]])

In [115]:
price_per_unit=([20,30,15])
units_sold = ([[50,60,25],[10,13,5],[40,70,52]])

In [116]:
np.dot(price_per_unit,units_sold)

array([1900, 2640, 1430])

# Loss or Cost Function

## Mean Absolute Error

In [117]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [118]:
def mae(y_true,y_predicted):
    total_error = 0
    #Gives one value from both array for each iteration
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("Total error:",total_error)
    mae = total_error/len(y_true)
    print("MAE:",mae)
    return mae

In [119]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [120]:
#Mean Absolute Error using numpy
np.mean(np.abs(y_predicted - y_true))

0.5

In [121]:
def mae_np(y_true,y_predicted):
    return np.mean(np.abs(y_predicted-y_true))

In [122]:
mae_np(y_predicted,y_true)

0.5

## Mean Squared Error(MSE)

In [123]:
def mse(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=pow(yp-yt
                         ,2)
    print("Total Error:",total_error)
    mse= total_error/len(y_true)
    print("MSE:",mse)
    return mse

In [124]:
mse(y_true,y_predicted)

Total Error: 1.83
MSE: 0.366


0.366

In [151]:
#Using numpy
np.mean(np.power(y_predicted-y_true,2))

0.366

## Log Function

In [125]:
#Take a value which is very close to 0 but not 0 or else it would be not defined
np.log([0.000000000000000001])

array([-41.44653167])

In [126]:
y_predicted = np.array(y_predicted)

In [127]:
#If you have value 1 in y_pred it will replace it to close to 1 so as to avoid log[0] condn
epsilon=1e-15

In [135]:
y_predicted_new=np.maximum(y_predicted,epsilon)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [136]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]

In [137]:
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [138]:
y_predicted_new= np.array(y_predicted_new)

In [139]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

## Log Loss

In [146]:

def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)  # Use np.clip to ensure values are within range
    y_predicted_new = np.array(y_predicted_new)
    
    # Calculate the logarithmic loss with small value added to avoid log(0)
    loss = -np.mean(y_true * np.log(y_predicted_new + epsilon) + (1 - y_true) * np.log(1 - y_predicted_new + epsilon))
    
    return loss


In [147]:
log_loss(y_true,y_predicted)

16.922934522814046