In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ["nice food",
          "amazing restaurant",
          "too good",
          "just loved it!",
          "will go again",
          "horrible food",
          "never go there",
          "poor service",
          "poor quality",
          "needs improvement"]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [23]:
#Converting into One Hot Vector 
#Assigned 'amazing' number:17, & 'restaurant' : number :29
one_hot("amazing restaurant",40)

[14, 15]

In [24]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[27, 24], [17, 29], [10, 3], [11, 1, 22], [14, 13, 16], [7, 24], [2, 13, 22], [5, 4], [5, 17], [14, 29]]


In [25]:
max_length = 3
#Supplying all encoded reviews into padded sequences
# padding ="post": pad the reviews towards the end
padded_reviews = pad_sequences(encoded_reviews, maxlen= max_length, padding ="post")
padded_reviews
#Now, every vector size is 3

array([[27, 24,  0],
       [17, 29,  0],
       [10,  3,  0],
       [11,  1, 22],
       [14, 13, 16],
       [ 7, 24,  0],
       [ 2, 13, 22],
       [ 5,  4,  0],
       [ 5, 17,  0],
       [14, 29,  0]], dtype=int32)

In [26]:
embedded_vector_size = 4

#1st layer will be embedding layer
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length= max_length, name ="embedding"))
#Flatten the layer
model.add(Flatten())
#Next layer would be 1 neuron sigmoid activation function
model.add(Dense(1,activation='sigmoid'))

In [27]:
X = padded_reviews
y = sentiment

In [28]:
#Since, review can be +/- :binary_crossentropy
model.compile(optimizer = 'adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.fit(X, y, epochs =50,verbose =0)

In [30]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 63ms/step - loss: 0.6441 - accuracy: 0.9000


In [31]:
#Extract weights
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [32]:
weights[27]

array([-0.06857188,  0.03978147,  0.04583412,  0.04156191], dtype=float32)

In [33]:
weights[24]

array([-0.02820498,  0.03644514,  0.00530653,  0.02175176], dtype=float32)